title: S.Mona
description: "smona's blog.share everything that I've learn"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://silbertmonaphia.github.io" # the base hostname & protocol for your site, e.g. http://example.com
email: silbertmonaphia@gmail.com
twitter_username: silbertmonaphia
github_username:  silbertmonaphia
permalink: /:title.html

# Build settings
markdown: kramdown
toc_levels: 1..6


plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Pagination
paginate: 20
paginate_path: "page/:num/"

# SiteMap

# prose.io config
prose:
    rooturl: '_posts'
    siteurl: 'https://silbertmonaphia.github.io/'

# Google Analytics
